export * from "./Banner";
export { default as ExamDetailBanner } from "./Banner";
export * from "./Description";
export { default as ExamDetailDescription } from "./Description";
export * from "./Header";
export { default as ExamDetailHeader } from "./Header";
export * from "./QRCodeCard";
export { default as ExamDetailQRCodeCard } from "./QRCodeCard";
export * from "./Rating";
export { default as ExamDetailRating } from "./Rating";
export * from "./RetentionRate";
export { default as ExamDetailRetentionRate } from "./RetentionRate";
export * from "./UsersCount";
export { default as ExamDetailUsersCount } from "./UsersCount";
